name: Identity Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - '1-identity/**'
jobs:
  preview:
    uses: ./.github/workflows/pull_request.yml
    with:
      pulumi-project: ./1-identity
      assume-role: identity-deployer
    secrets:
      pulumi-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      tunnel-token-id: ${{ secrets.TUNNEL_TOKEN_ID }}
      tunnel-token-secret: ${{ secrets.TUNNEL_TOKEN_SECRET }}
