name: Managed Infrastructure Merge
on:
  push:
    branches:
      - main
    paths:
      - '2-managed-infrastructure/**'
jobs:
  deploy:
    uses: ./.github/workflows/merge.yml
    with:
      pulumi-project: ./2-managed-infrastructure
      assume-role: infrastructure-deployer
    secrets:
      pulumi-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      tunnel-token-id: ${{ secrets.TUNNEL_TOKEN_ID }}
      tunnel-token-secret: ${{ secrets.TUNNEL_TOKEN_SECRET }}
