name: Cluster Services Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - '3-cluster-services/**'
jobs:
  preview:
    uses: ./.github/workflows/pull_request.yml
    with:
      pulumi-project: ./3-cluster-services
    secrets:
      pulumi-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      tunnel-token-id: ${{ secrets.TUNNEL_TOKEN_ID }}
      tunnel-token-secret: ${{ secrets.TUNNEL_TOKEN_SECRET }}
