name: Managed Apps Merge
on:
  push:
    branches:
      - main
    paths:
      - '6-managed-apps/**'
jobs:
  deploy:
    uses: ./.github/workflows/merge.yml
    with:
      pulumi-project: ./6-managed-apps
      assume-role: infrastructure-deployer
    secrets:
      pulumi-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      tunnel-token-id: ${{ secrets.TUNNEL_TOKEN_ID }}
      tunnel-token-secret: ${{ secrets.TUNNEL_TOKEN_SECRET }}
