name: Pull Request
on:
  workflow_call:
    inputs:
      pulumi-project:
        required: true
        type: string
    secrets:
      pulumi-token:
        required: true
      tunnel-token-id:
        required: true
      tunnel-token-secret:
        required: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Tunnel
        run: |
          docker run \
            -d \
            -p 1234:1234 \
            cloudflare/cloudflared:2022.3.1 \
            access tcp \
              --hostname=k8s.andrewmeier.dev \
              --url=0.0.0.0:1234 \
              --service-token-id=${{ secrets.tunnel-token-id }} \
              --service-token-secret=${{ secrets.tunnel-token-secret }}
      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm install
        working-directory: ${{ inputs.pulumi-project }}
      - name: Preview Changes
        uses: pulumi/actions@v3
        with:
          work-dir: ${{ inputs.pulumi-project }}
          command: preview
          stack-name: prod
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi-token }}
