name: Pulumi Preview
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Packages
        run: npm install
        working-directory: ${{ inputs.project }}
      - name: Preview Changes
        uses: pulumi/actions@v3
        with:
          work-dir: ${{ inputs.project }}
          command: preview
          stack-name: prod
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.token }}
