name: Start K8s API Tunnel
on:
  workflow_call:
    secrets:
      service-token-id:
        required: true
      service-token-secret:
        required: true

jobs:
  start-tunnel:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Start Tunnel
        run: |
          docker run \
            -d \
            -p 1234:1234 \
            cloudflare/cloudflared:2022.3.1 \
            access tcp \
              --hostname=k8s.andrewmeier.dev \
              --url=0.0.0.0:1234 \
              --service-token-id=${{ secrets.service-token-id }} \
              --service-token-secret=${{ secrets.service-token-secret }}
